modLoader="javafml"
loaderVersion="[47,)" 
license="All Rights Reserved"

[[mods]]
modId="scuffedsouls"
version="1.0.0"
displayName="ScuffedSouls"
authors="YaseruXD"
description='''
Just a soon to be core mod for the Scuffed Souls Modpack.
'''

[[dependencies.scuffedsouls]]
modId="epic_stats_mod_remastered"
mandatory=true
versionRange="[2.0.1,)"
ordering="AFTER"
side="BOTH"





