modLoader="javafml"
loaderVersion="[47,)" 
license="All Rights Reserved"

[[mods]]
modId="scuffedsouls"
version="1.0.0"
displayName="ScuffedSouls"
authors="YaseruXD"
description='''
Just a soon to be core mod for the Scuffed Souls Modpack.
'''

[[dependencies.scuffedsouls]]
modId="epic_stats_mod_remastered"
mandatory=true
versionRange="[2.0.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.scuffedsouls]]
modId="combat_evolution"
mandatory=true
versionRange="[2.2.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.scuffedsouls]]
modId="epicfight"
mandatory=true
versionRange="[20.14.17,)"
ordering="AFTER"
side="BOTH"

[[dependencies.scuffedsouls]]
modId="epicfightx"
mandatory=true
versionRange="[1.2.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.scuffedsouls]]
modId="epicfight_dd"
mandatory=true
versionRange="[20.14.1.18.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.scuffedsouls]]
modId="efn"
mandatory=true
versionRange="[3.4.1,)"
ordering="AFTER"
side="BOTH"







